name: Example Workflow with ID Token

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permiso para generar un token OIDC
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Mostrar permisos
        run: echo "Permisos configurados correctamente para id-token:write"
